/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Invoice;

import static java.lang.Integer.parseInt;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import ketnoidatabase.DataProvider;

/**
 *
 * @author henryangminh
 */
public class addProducts extends javax.swing.JFrame {
    private String InvoiceID;

    /**
     * Creates new form JFrame
     */
    public addProducts() {
        initComponents();
    }
    
    public addProducts(String InvoiceID) {
        initComponents();
        Combo();
        this.InvoiceID=InvoiceID;
        lblInvoiceID.setText(InvoiceID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        slcProductID = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        nbrQuantities = new javax.swing.JSpinner();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblProductName = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblSize = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblProductType = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lblInvoiceID = new javax.swing.JLabel();
        btnAddProducts = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Arial", 0, 48)); // NOI18N
        jLabel1.setText("Thêm Hàng");

        slcProductID.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        slcProductID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                slcProductIDActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel2.setText("Mã Hàng Hóa");

        nbrQuantities.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        nbrQuantities.setModel(new javax.swing.SpinnerNumberModel(1, 1, null, 1));
        nbrQuantities.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                nbrQuantitiesStateChanged(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel3.setText("Số Lượng");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel4.setText("Tên Hàng Hóa: ");

        lblProductName.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblProductName.setText("xxx");

        jLabel6.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel6.setText("Size:");

        lblSize.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblSize.setText("xxx");

        jLabel8.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel8.setText("Loại:");

        lblProductType.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblProductType.setText("xxx");

        jLabel10.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel10.setText("Đơn Giá:");

        lblPrice.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblPrice.setText("xxx");

        jLabel12.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        jLabel12.setText("Giới Tính:");

        lblGender.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        lblGender.setText("xxx");

        jLabel14.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel14.setText("Mã Đơn Hàng:");

        lblInvoiceID.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblInvoiceID.setText("xxx");

        btnAddProducts.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnAddProducts.setText("Thêm");
        btnAddProducts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddProductsActionPerformed(evt);
            }
        });

        btnExit.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        btnExit.setText("Hủy");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel5.setText("Thành Tiền:");

        lblSubTotal.setFont(new java.awt.Font("Arial", 0, 36)); // NOI18N
        lblSubTotal.setText("xxx");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnAddProducts)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnExit)
                                .addGap(43, 43, 43))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(jLabel2)
                                                    .addComponent(jLabel3))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(slcProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(nbrQuantities, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(lblSubTotal)
                                                .addGap(105, 105, 105)))
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel8)))
                                    .addComponent(jLabel5)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblInvoiceID)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProductType)
                            .addComponent(lblGender)
                            .addComponent(lblPrice)
                            .addComponent(lblProductName)
                            .addComponent(lblSize)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(jLabel1)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblProductType)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblGender)
                        .addGap(11, 11, 11)
                        .addComponent(lblPrice)
                        .addGap(23, 23, 23))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(slcProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(lblProductName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(nbrQuantities, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(lblSize))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(jLabel10))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblSubTotal)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(lblInvoiceID))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddProducts)
                    .addComponent(btnExit))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void slcProductIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_slcProductIDActionPerformed
        // TODO add your handling code here:
        if(slcProductID.getSelectedItem().toString()!="")
        {
            String sql="SELECT * FROM Product INNER JOIN ProductType WHERE ProductID='"+slcProductID.getSelectedItem().toString()+"' AND Product.ProductType=ProductType.ProductTypeID";
            try {
                String[] Size = {"","S","M","L","XL"};
                String[] Gender = {"","Nam","Nữ","Unisex"};
                ResultSet rs = DataProvider.executeQuery(sql);
                if(rs.next())
                {
                    lblProductName.setText(rs.getString("ProductName"));
                    lblSize.setText(Size[rs.getInt("Size")]);
                    lblProductType.setText(rs.getString("ProductTypeName"));
                    lblGender.setText(Gender[rs.getInt("Gender")]);
                    lblPrice.setText(rs.getString("Price"));
                    int SubTotal=rs.getInt("Price")*Integer.parseInt(nbrQuantities.getValue().toString());
                    lblSubTotal.setText(Integer.toString(SubTotal));
                }
            } catch (Exception ex) {
                System.out.print(ex);
            }
        }
        else
        {
            lblProductName.setText("");
            lblSize.setText("");
            lblProductType.setText("");
            lblGender.setText("");
            lblPrice.setText("");
            lblSubTotal.setText("0");
        }
    }//GEN-LAST:event_slcProductIDActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        try {
            // TODO add your handling code here:
            editInvoice EditInvoice = new editInvoice(InvoiceID);
            EditInvoice.show();
            setVisible(false);
            dispose();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void nbrQuantitiesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_nbrQuantitiesStateChanged
        // TODO add your handling code here:
        int SubTotal = parseInt(lblPrice.getText())*Integer.parseInt(nbrQuantities.getValue().toString());
        lblSubTotal.setText(Integer.toString(SubTotal));
    }//GEN-LAST:event_nbrQuantitiesStateChanged

    private void btnAddProductsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddProductsActionPerformed
        // TODO add your handling code here:
        String sql = "INSERT INTO InvoiceDetails (InvoiceID, ProductID, Quantities, SubTotal) VALUES ('"+InvoiceID+"', '"+slcProductID.getSelectedItem().toString()+"', '"+nbrQuantities.getValue().toString()+"', '"+lblSubTotal.getText()+"') ";
        try {
            DataProvider.executeSql(sql);
            sql="UPDATE Invoice SET Total = (SELECT SUM(SubTotal) FROM InvoiceDetails WHERE InvoiceID='"+InvoiceID+"') WHERE InvoiceID='"+InvoiceID+"'";
            DataProvider.executeSql(sql);
            JOptionPane.showMessageDialog(null, "Thêm Hàng Thành Công","THÔNG BÁO",1);
            editInvoice EditInvoice = new editInvoice(InvoiceID);
            EditInvoice.show();
            setVisible(false);
            dispose();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_btnAddProductsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddProducts;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblInvoiceID;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblProductType;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JSpinner nbrQuantities;
    private javax.swing.JComboBox<String> slcProductID;
    // End of variables declaration//GEN-END:variables

    private void Combo()
    {
        String sql="SELECT ProductID FROM Product";
        try {
            ResultSet rs = DataProvider.executeQuery(sql);
            slcProductID.addItem("");
            while(rs.next())
                slcProductID.addItem(rs.getString("ProductID"));
        } catch (SQLException ex) {
        }
    }
}
